#ifndef __DO_RMAHDR_
#define __DO_RMAHDR_

#ifdef __cplusplus
  extern "C" {
#endif

typedef unsigned long UP;
typedef unsigned U;
typedef unsigned char UB;
typedef unsigned char scalar;
typedef struct vec32 vec32;
typedef unsigned short US;
typedef unsigned char SVAL;
typedef unsigned char TYPEB;
typedef struct qird QIRD;
typedef unsigned char UST_e;
typedef unsigned uscope_t;
typedef U  NumLibs_t;
struct vec32 {
    U  I1;
    U  I2;
};
typedef unsigned RP;
typedef unsigned RO;
typedef unsigned long long ULL;
typedef U  GateCount;
typedef U  NodeCount;
typedef unsigned short HsimEdge;
typedef unsigned char HsimExprChar;
typedef struct {
    U  I672;
    RP  I673;
} RmaReceiveClock1;
typedef NodeCount  FlatNodeNum;
typedef U  InstNum;
typedef unsigned long long TimeStamp64;
typedef U  TimeStamp;
typedef enum {
    PD_SING = 0,
    PD_RF = 1,
    PD_PLSE = 2,
    PD_PLSE_RF = 3,
    PD_NULL = 4
} PD_e;
typedef TimeStamp  RmaTimeStamp;
typedef TimeStamp64  RmaTimeStamp64;
typedef union {
    double I692;
    unsigned long long I693;
    unsigned  I694[2];
} rma_clock_struct;
typedef struct eblk EBLK;
typedef int (* E_fn)(void);
typedef struct eblk {
    struct eblk * I701;
    E_fn  I702;
    struct iptmpl * I703;
    unsigned I705;
    struct eblk * I706;
} eblk_struct;
typedef struct {
    RP  I701;
    RP  I702;
    RP  I703;
    unsigned I705;
    RP  I706;
} RmaEblk;
typedef union {
    double I692;
    unsigned long long I693;
    unsigned  I694[2];
} clock_struct;
typedef clock_struct  RmaClockStruct;
typedef struct RmaRetain_t RmaRetain;
struct RmaRetain_t {
    RP  I742;
    RmaEblk  I700;
    U  I743;
    US  I744 :1;
    US  I745 :4;
    US  I183 :2;
    US  state :2;
    US  I747 :1;
    US  I748 :2;
    US  I749 :2;
    US  fHsim :1;
    US  I555 :1;
    scalar  newval;
    scalar  I751;
    RP  I752;
};
typedef struct MPSched MPS;
typedef struct RmaMPSched RmaMps;
struct MPSched {
    MPS  * I732;
    scalar  I733;
    scalar  I734;
    scalar  I735;
    scalar  fHsim :1;
    scalar  I183 :6;
    U  I737;
    EBLK  I738;
    void * I739;
    UP   I740[1];
};
struct RmaMPSched {
    RP  I732;
    scalar  I733;
    scalar  I734;
    scalar  I735;
    scalar  fHsim :1;
    scalar  I183 :6;
    U  I737;
    RmaEblk  I738;
    RP  I739;
    RP   I740[1];
};
typedef struct RmaMPSchedPulse RmaMpsp;
struct RmaMPSchedPulse {
    RP  I732;
    scalar  I733;
    scalar  I734;
    scalar  I735;
    scalar  I183;
    U  I737;
    RmaEblk  I738;
    scalar  I749;
    scalar  I756;
    scalar  I757;
    scalar  I758;
    U  I759;
    RmaClockStruct  I760;
    RmaClockStruct  I761;
    U  state;
    U  I762;
    RP  I703;
    RP  I763;
    RP  I764;
    RP   I740[1];
};
typedef struct MPItem MPI;
struct MPItem {
    U  * I766;
    void * I767;
};
typedef struct {
    RmaEblk  I700;
    RP  I768;
    scalar  I769;
    scalar  I749;
    scalar  I770;
} RmaTransEventHdr;
typedef struct RmaMPSchedPulseNewCsdf RmaMpspNewCsdf;
struct RmaMPSchedPulseNewCsdf {
    RP  I732;
    scalar  I733;
    scalar  I734;
    scalar  I735;
    scalar  fHsim :1;
    scalar  I183 :6;
    U  I737;
    RmaEblk  I738;
    scalar  I749;
    scalar  I756;
    scalar  I757;
    scalar  I758;
    U  state :4;
    U  I772 :28;
    RmaClockStruct  I760;
    RmaClockStruct  I761;
    RP  I773;
    RP  I703;
    RP  I774;
    RP   I740[1];
};
typedef struct red_t {
    U  I775;
    U  I776;
    U  I655;
} RED;
typedef struct predd {
    PD_e  I183;
    RED   I777[0];
} PREDD;
union rhs_value {
    vec32  I778;
    scalar  I769;
    vec32  * I749;
    double I779;
    U  I780;
};
typedef struct nbs_t {
    struct nbs_t * I781;
    struct nbs_t * I783;
    void (* I784)(struct nbs_t * I785);
    unsigned I786 :1;
    unsigned I787 :1;
    unsigned I788 :1;
    unsigned I789 :1;
    unsigned I790 :27;
    void * I791;
    U  I792;
    union rhs_value I793;
    vec32  I692;
    union {
        struct nbs_t * first;
        struct nbs_t * last;
    } I795;
} NBS;
typedef struct {
    RP  I796;
    RP  I763;
    RP  I703;
    RP  I764;
    RmaEblk  I700;
    RmaEblk  I797;
    RP  I798;
    scalar  I769;
    scalar  I749;
    char state;
    uscope_t  I799;
    U  I800;
    RP  I801;
    scalar  I756;
    scalar  I757;
    scalar  I758;
    RmaClockStruct  I760;
    RmaClockStruct  I761;
    RP  I739;
} RmaPulse;
typedef struct {
    int * I802;
    long long I803;
} TypeData;
struct etype {
    U  I571 :8;
    U  I572 :24;
    U  I573;
    U  I574 :1;
    U  I575 :1;
    U  I576 :1;
    U  I577 :1;
    U  I578 :1;
    U  I579 :1;
    U  I580 :1;
    U  I581 :1;
    U  I582 :1;
    U  I583 :4;
    U  I584 :1;
    U  I585 :1;
    U  I586 :1;
    U  I587 :1;
    U  I588 :1;
    U  I589 :1;
    U  I590 :1;
    U  I591 :1;
    U  I592 :2;
    U  I593 :1;
    U  I594 :2;
    U  I595 :1;
    U  I596 :1;
    U  I597 :1;
    U  I598 :1;
    U  I599 :2;
    TypeData  * I600;
    U  I601;
    U  I602;
    U  I603 :1;
    U  I604 :1;
    U  I605 :1;
    U  I606 :1;
    U  I607 :2;
    U  I608 :2;
    U  I609 :1;
    U  I610 :1;
    U  I611 :1;
    U  I612 :1;
    U  I613 :1;
    U  I614 :1;
    U  I615 :1;
    U  I616 :1;
    U  I617 :16;
};
typedef enum {
    QIRDModuleC = 1,
    QIRDSVPackageC = 2,
    QIRDSpiceModuleC = 3
} QIRDModuleType;
typedef struct {
    U  I807 :1;
    U  I808 :1;
    U  I809 :1;
    U  I810 :1;
    U  I811 :1;
    U  I812 :1;
    U  I813 :1;
    U  I814 :1;
    U  I815 :1;
    U  I816 :1;
    U  I817 :1;
    U  I818 :1;
    U  I819 :1;
    U  I820 :1;
    U  I821 :1;
    U  I822 :1;
    U  I823 :1;
    U  I824 :1;
    QIRDModuleType  I825 :2;
    U  I826 :1;
    U  I827 :1;
    U  I828 :1;
    U  I829 :1;
    U  I830 :1;
    U  I831 :1;
    U  I832 :1;
    U  I833 :1;
    U  I834 :1;
    U  I835 :1;
    U  I836 :1;
    U  I837 :1;
    U  I838 :1;
    U  I839 :1;
    U  I840 :1;
    U  I841 :1;
    U  I842 :1;
} BitFlags;
struct qird {
    US  I4;
    US  I5;
    U  I6;
    U  I7;
    char * I8;
    char * I9;
    U  * I10;
    char * I11;
    char * I12;
    U  I13;
    U  I14;
    struct vcd_rt * I15;
    U  I17;
    struct _vcdOffset_rt * I18;
    UP  * I20;
    U  I21;
    UP  * I22;
    U  I23;
    U  I24;
    U  I25;
    U  * I26;
    U  * I27;
    void * I28;
    void * I29;
    U  I30;
    int I31;
    UP  I32;
    U  I33;
    U  I34;
    U  I35;
    UP  I36;
    U  * I37;
    UP  I38;
    U  I39;
    BitFlags  I40;
    U  I41;
    U  I42;
    U  I43;
    U  I44;
    U  I45;
    U  * I46;
    U  I47;
    U  * I48;
    U  I49;
    U  I50;
    U  I51;
    U  I52;
    U  I53;
    U  I54;
    U  I55;
    U  * I56;
    U  * I57;
    U  I58;
    U  I59;
    U  * I60;
    U  I61;
    U  * I62;
    U  I63;
    U  I64;
    U  I65;
    U  I66;
    U  * I67;
    U  I68;
    U  * I69;
    U  I70;
    U  I71;
    U  I72;
    U  I73;
    U  I74;
    U  I75;
    U  * I76;
    char * I77;
    U  I78;
    U  I79;
    U  I80;
    U  I81;
    U  I82;
    U  * I83;
    U  I84;
    U  I85;
    UP  * I86;
    U  I87;
    U  I88;
    UP  * I89;
    U  I90;
    U  I91;
    U  I92;
    U  I93;
    U  I94;
    U  I95;
    U  * I96;
    U  I97;
    U  I98;
    U  * I99;
    U  * I100;
    U  * I101;
    U  * I102;
    U  * I103;
    U  I104;
    U  I105;
    struct taskInfo * I106;
    U  I108;
    U  I109;
    int * I110;
    UP  * I111;
    U  * I112;
    U  I113;
    U  I114;
    U  I115;
    U  I116;
    U  I117;
    struct qrefer * I118;
    U  * I120;
    unsigned * I121;
    void * I122;
    U  I123;
    U  I124;
    struct classStaticReferData * I125;
    U  I127;
    U  * I128;
    U  I129;
    struct wakeupInfoStruct * I130;
    U  I132;
    U  I133;
    U  I134;
    U  * I135;
    U  I136;
    U  * I137;
    U  I138;
    U  I139;
    U  I140;
    U  * I141;
    U  I142;
    U  * I143;
    U  I144;
    U  I145;
    U  * I146;
    U  I147;
    U  I148;
    U  * I149;
    U  * I150;
    U  * I151;
    U  I152;
    U  I153;
    U  I154;
    U  I155;
    U  I156;
    struct qrefee * I157;
    U  * I159;
    U  I160;
    struct qdefrefee * I161;
    U  * I163;
    int (* I164)(void);
    char * I165;
    U  I166;
    U  I167;
    void * I168;
    void * I169;
    NumLibs_t  I170;
    char * I171;
    U  * I172;
    U  I173;
    U  I174;
    U  I175;
    U  I176;
    U  I177;
    U  * I178;
    U  * I179;
    int I180;
    struct clock_load * I181;
    int I196;
    struct clock_data * I197;
    int I213;
    struct clock_hiconn * I214;
    U  I218;
    int I219;
    U  I220;
    int I221;
    U  * I222;
    U  * I223;
    U  I224;
    void * I225;
    U  I226;
    U  I227;
    UP  * I228;
    void * I229;
    U  I230;
    UP  * I231;
    U  * I232;
    int (* I233)(void);
    U  * I234;
    UP  * I235;
    U  * I236;
    U  I237 :1;
    U  I238 :31;
    U  I239;
    U  I240;
    UP  * I241;
    U  * I242;
    U  I243 :1;
    U  I244 :1;
    U  I245 :1;
    U  I246 :1;
    U  I247 :28;
    U  I248;
    U  I249;
    U  I250;
    U  I251 :31;
    U  I252 :1;
    UP  * I253;
    UP  * I254;
    U  * I255;
    U  * I256;
    U  * I257;
    UP  * I258;
    UP  * I259;
    UP  * I260;
    U  * I261;
    UP  * I262;
    UP  * I263;
    UP  * I264;
    char * I265;
    U  I266;
    U  I267;
    U  I268;
    UP  * I269;
    UP  * I270;
    UP  * I271;
    UP  * I272;
    UP  * I273;
    UP  * I274;
    UP  * I275;
    UP  * I276;
    UP  * I277;
    UP  * I278;
    UP  * I279;
    UP  * I280;
    UP  * I281;
    U  * I282;
    U  * I283;
    UP  * I284;
    U  I285;
    U  I286;
    U  I287;
    U  I288;
    U  I289;
    U  I290;
    U  I291;
    U  I292;
    char * I293;
    U  * I294;
    U  I295;
    U  I296;
    U  I297;
    U  I298;
    U  I299;
    UP  * I300;
    UP  * I301;
    UP  * I302;
    UP  * I303;
    struct daidirInfo * I304;
    struct vcs_tftable * I306;
    U  I308;
    UP  * I309;
    UP  * I310;
    U  I311;
    U  I312;
    U  I313;
    UP  * I314;
    U  * I315;
    struct qird_hil_data * I316;
    UP  (* I318)(void);
    UP  (* I319)(void);
    UP  (* I320)(void);
    UP  (* I321)(void);
    UP  (* I322)(void);
    int * I323;
    int (* I324)(void);
    char * I325;
    UP  * I326;
    UP  * I327;
    UP  (* I328)(void);
    int (* I329)(void);
    int * I330;
    int (* I331)(void);
    int * I332;
    char * I333;
    U  * I334;
    U  * I335;
    U  * I336;
    U  * I337;
    void * I338;
    U  I339;
    void * I340;
    U  I341;
    U  I342;
    U  I343;
    U  I344;
    U  I345;
    U  I346;
    UP  * I347;
    U  * I348;
    U  * I349;
    U  I350 :15;
    U  I351 :14;
    U  I352 :1;
    U  I353 :1;
    U  I354 :1;
    U  I355 :3;
    U  I356 :1;
    U  I357 :1;
    U  I358 :17;
    U  I359 :3;
    U  I360 :5;
    U  I361 :2;
    U  I362 :1;
    U  I363 :31;
    struct scope * I364;
    U  I366;
    U  I367;
    U  I368;
    U  * I369;
    U  * I370;
    U  * I371;
    U  I372;
    U  I373;
    U  I374;
    struct pcbt * I375;
    U  I385;
    U  I386;
    U  I387;
    U  I388;
    void * I389;
    void * I390;
    void * I391;
    int I392;
    U  * I393;
    U  I394;
    U  I395;
    U  I396;
    U  I397;
    U  I398;
    U  I399;
    U  I400;
    void * I401;
    UP  * I402;
    U  I403;
    U  I404;
    void * I405;
    U  I406;
    void * I407;
    U  I408;
    void * I409;
    U  I410;
    int (* I411)(void);
    int (* I412)(void);
    void * I413;
    void * I414;
    void * I415;
    U  I416;
    U  I417;
    U  I418;
    U  I419;
    U  I420;
    U  I421;
    char * I422;
    U  I423;
    U  * I424;
    U  I425;
    U  * I426;
    U  I427;
    U  I428;
    U  I429;
    U  I430;
    U  I431;
    U  I432;
    U  * I433;
    U  I434;
    U  I435;
    U  * I436;
    U  I437;
    U  I438;
    U  * I439;
    char * I440;
    U  I441;
    U  I442;
    U  I443;
    U  I444;
    U  * I445;
    U  * I446;
    U  I447;
    U  * I448;
    U  * I449;
    U  I450;
    U  I451;
    U  I452;
    U  I453;
    struct cosim_info * I454;
    U  I456;
    U  * I457;
    U  I458;
    void * I459;
    U  I460;
    U  * I461;
    U  I462;
    U  * I463;
    U  I464;
    U  I465;
    U  * I466;
    U  I467;
    U  * I468;
    U  I469;
    U  * I470;
    U  I471;
    U  I472;
    U  I473;
    U  I474;
    U  I475;
    U  I476;
    U  I477;
    U  I478;
    U  I479;
    U  * I480;
    U  * I481;
    void (* I482)(void);
    U  * I483;
    UP  * I484;
    struct mhdl_outInfo * I485;
    UP  * I487;
    U  I488;
    UP  * I489;
    U  I490;
    void * I491;
    U  * I492;
    void * I493;
    char * I494;
    int (* I495)(void);
    U  * I496;
    char * I497;
    char * I498;
    U  I499;
    U  * I500;
    char * I501;
    U  I502;
    struct regInitInfo * I503;
    UP  * I505;
    U  * I506;
    char * I507;
    U  I508;
    U  I509;
    U  I510;
    U  I511;
    U  I512;
    U  I513;
    U  I514;
    U  I515;
    UP  * I516;
    U  I517;
    U  I518;
    U  I519;
    U  I520;
    UP  * I521;
    U  I522;
    UP  * I523;
    U  I524;
    U  I525;
    U  I526;
    U  * I527;
    U  I528;
    U  I529;
    U  I530;
    U  * I531;
    U  * I532;
    UP  * I533;
    UP  * I534;
    void * I535;
    UP  I536;
    void * I537;
    void * I538;
    void * I539;
    void * I540;
    void * I541;
    UP  I542;
    U  * I543;
    U  * I544;
    void * I545;
    U  I546 :1;
    U  I547 :31;
    U  I548;
    U  I549;
    U  I550;
    int I551;
    U  I552 :1;
    U  I553 :1;
    U  I554 :1;
    U  I555 :29;
    void * I556;
    void * I557;
    void * I558;
    void * I559;
    UP  * I560;
    U  * I561;
    U  I562;
    char * I563;
    U  * I564;
    U  * I565;
    char * I566;
    int * I567;
    UP  * I568;
    struct etype * I569;
    U  I618;
    U  I619;
    U  I620;
    U  * I621;
    void * I622;
    U  I623;
    U  I624;
    void * I625;
    U  I626;
    U  I627;
    U  * I628;
    U  I629;
    U  * I630;
    U  I631;
    U  I632;
    U  * I633;
};
typedef struct pcbt {
    U  * I377;
    UP  I378;
    U  I379;
    U  I380;
    U  I381;
    U  I382;
    U  I383;
    U  I384;
} PCBT;
struct iptmpl {
    QIRD  * I707;
    struct vcs_globals_t * I708;
    void * I710;
    UP  I711;
    UP  I712;
    struct iptmpl * I703[2];
};
typedef unsigned long long FileOffset;
typedef struct _hsimPeriodL {
    char  I893[256];
    struct _hsimPeriodL * I847;
} HsimPeriodL;
typedef struct {
    U   I895[2];
    U  I896 :1;
    U  I897 :1;
    U  I898 :8;
    U  I899 :8;
    U  I900 :8;
    U  I901 :4;
    unsigned long long I902;
    unsigned long long I903;
    unsigned long long I904;
    unsigned long long I905;
    unsigned long long I906;
    U  I907;
    U  I908;
    U  I909;
    U  I910;
    HsimPeriodL  * I911;
    HsimPeriodL  * I912;
    U  I913;
} HsimSignalMonitor;
typedef struct {
    FlatNodeNum  I914;
    InstNum  I915;
    U  I855;
    scalar  I916;
    UB  I917;
    UB  I918;
    UB  I919;
    UB  I920;
    U  I921;
    U  I922;
    U  I923;
    U  I924;
    U  I925;
    U  I926;
    HsimSignalMonitor  * I927;
    RP  I928;
    RmaTimeStamp64  I929;
    U  I930;
    RmaTimeStamp64  I931;
} HsimNodeRecord;
typedef struct {
    RP  I932;
    RP  I703;
} RmaIbfIp;
typedef struct {
    RP  I932;
    RP  pcode;
} RmaIbfPcode;
typedef struct {
    RmaEblk  I700;
} RmaEvTriggeredOrSyncLoadCg;
typedef struct {
    RmaEblk  I700;
    RP  I933;
} RmaAnySchedSampleSCg;
typedef struct {
    RmaEblk  I700;
    RP  I934;
    RP  I933;
    vec32  I935;
} RmaAnySchedVCg;
typedef struct {
    RmaEblk  I700;
    RP  I934;
    RP  I933;
    vec32   I748[1];
} RmaAnySchedWCg;
typedef struct {
    RmaEblk  I700;
    RP  I934;
    RP  I933;
    scalar   I936[1];
} RmaAnySchedECg;
typedef struct {
    RP  I937;
} RmaRootCbkCg;
typedef struct {
    RP  I938;
} RmaRootVcdCg;
typedef struct {
    RP  I939;
} RmaRootForceCbkCg;
typedef struct {
    RmaEblk  I700;
    RP  I940;
} RmaForceCbkJmpCg;
typedef struct {
    U  I5;
    U  I696 :30;
    U  I941 :1;
    U  I942 :1;
    vec32  I778;
    U  I943;
    RP  I944;
    RP  I945;
} RmaForceSelectorV;
typedef struct {
    U  I5;
    RmaIbfPcode  I951;
} RmaNetTypeDriverGate;
typedef struct {
    U  I5;
    U  I638;
    RmaIbfPcode   I951[1];
} RmaNetTypeScatterGate;
typedef struct {
    U  I5;
    RmaIbfPcode  I951;
} RmaNetTypeGatherGate;
typedef struct {
    RmaIbfPcode  I952;
    U  I953 :3;
    U  I954 :1;
    U  I955 :1;
    U  I956 :16;
} RmaNbaGateOfn;
typedef struct {
    NBS  I957;
    RmaIbfPcode  I952;
} RmaNbaGate1;
typedef struct {
    RP  ptable;
    RP  pfn;
    RP  pcode;
} Rma1InputGateFaninCgS;
typedef struct {
    U  I5;
    U  iinput;
    RP  I960;
} RmaCondOptLoad;
typedef struct {
    U  I5;
    U  iinput;
    RP  I960;
} RmaMacroStateUpdate;
typedef struct {
    U  I5;
    U  state;
    U  I961;
    U  * I962;
} RmaMacroState;
typedef struct {
    U  iinput;
    RP  I963;
} RmaMultiInputLogicGateCg;
typedef struct {
    U  iinput;
    RP  ptable;
    RP  I963;
} RmaSeqPrimEdgeInputCg;
typedef struct {
    RmaEblk  I700;
    RP  pcode;
} RmaSched0GateCg;
typedef struct {
    RmaEblk  I700;
    RP  pcode;
    RP  pfn;
} RmaUdpDeltaGateCg;
typedef struct {
    RmaEblk  I700;
    RP  pcode;
    RP  pfn;
    scalar  I964;
} RmaSchedDeltaGateCg;
typedef struct {
    UB  I965;
    RP  I966;
    RP  I967;
} RmaPropNodeSeqLhsSCg;
typedef struct {
    RmaEblk  I700;
    RP  pcode;
    U  I855;
    U   I689[1];
} RmaBitEdgeEblk;
typedef struct {
    U  I5;
    RP  I777;
    RmaEblk  I700;
    RmaIbfPcode  I952;
} RmaGateDelay;
typedef struct {
    U  I5;
    RP  I777;
    RmaEblk  I700;
    RmaIbfPcode  I952;
} RmaGateBehavioralDelay;
typedef struct {
    U  I5;
    union {
        RP  I1113;
        RP  I1378;
        RP  I1391;
    } I752;
    RmaIbfPcode  I952;
} RmaMPDelay;
typedef struct {
    U  I5;
    RmaPulse  I968;
    RmaIbfPcode  I952;
} RmaMPPulseHybridDelay;
typedef struct {
    U  I5;
    RmaIbfPcode  I952;
    RmaMps  I969;
} RmaMPHybridDelay;
typedef struct {
    U  I5;
    U  I970;
    RmaIbfPcode  I952;
    RmaEblk  I738;
} RmaMPHybridDelayPacked;
typedef struct {
    U  I5;
    RmaIbfPcode  I952;
    RmaMpspNewCsdf  I971;
} RmaMPPulseDelay;
typedef struct {
    U  I5;
    RmaMpsp  I971;
    RmaIbfPcode  I952;
} RmaMPPulseOptHybridDelay;
typedef struct _RmaBehavioralTransportDelay {
    U  I5;
    RP  I655;
    RmaTransEventHdr  I861;
    RP  I774;
    RmaIbfPcode  I952;
} RmaBehavioralTransportDelayS;
typedef struct {
    U  I5;
    U  I655;
    RmaTransEventHdr  I861;
    RP  I774;
    RmaIbfPcode  I952;
} RmaNtcTransDelay;
typedef struct {
    U  I5;
    U  I655;
    RmaEblk  I700;
    RmaIbfPcode  I952;
} RmaNtcTransMpwOptDelay;
typedef struct {
    U  I5;
    RmaEblk  I700;
    RmaIbfPcode  I952;
} RmaNtcTransZeroDelay;
typedef struct {
    U  I5;
    U  I972;
    U  I973;
    RmaTransEventHdr  I861;
    RP  I774;
    RmaIbfPcode  I952;
} RmaNtcTransDelayRF;
typedef struct {
    U  I5;
    U  I972;
    U  I973;
    RmaEblk  I700;
    RmaIbfPcode  I952;
} RmaNtcTransMpwOptDelayRF;
typedef struct {
    U  I5;
    RP  I974;
    RmaTransEventHdr  I861;
    RP  I774;
    RmaIbfPcode  I952;
} RmaICTransDelay;
typedef struct {
    U  I5;
    RP  I974;
    RmaEblk  I700;
    RmaIbfPcode  I952;
} RmaICTransMpwOptDelay;
typedef struct {
    U  I5;
    RmaEblk  I700;
    RmaIbfPcode  I952;
} RmaICTransZeroDelay;
typedef struct {
    U  I5;
    RP  I777;
    RmaEblk  I700;
    RmaIbfPcode  I952;
} RmaICSimpleDelay;
typedef struct {
    U  I5;
    union {
        RP  psimple;
        RP  I1378;
        RP  I1391;
    } I752;
    RmaIbfPcode  I952;
} RmaICDelay;
typedef struct {
    U  I5;
    RP  I777;
    RmaEblk  I700;
    RmaIbfPcode  I952;
} RmaPortDelay;
typedef struct {
    U  I5;
    RP   I975[(4)];
} RmaRtlXEdgesHdr;
typedef struct {
    U  I5;
    US  I976;
    US  I599;
    RP  I977;
    RP  I978;
    RP  I979;
} RmaRtlEdgeBlockHdr;
typedef struct {
    RP  I980;
    RP  I981;
} RemoteDbsedLoad;
typedef struct {
    RmaEblk  I700;
    US  I982;
    US  I599;
    U  I460;
    RP   I781[(4)];
    RP   I783[(4)];
    RemoteDbsedLoad   I983[1];
} RmaRtlEdgeBlock;
typedef struct TableAssign_ {
    struct TableAssign_ * I847;
    struct TableAssign_ * I768;
    U  I5;
    U  I985 :1;
    U  I986 :1;
    U  I987 :2;
    U  I988 :1;
    U  I672 :8;
    U  I599 :19;
    RP  ptable;
    RP  I963;
} TableAssign;
typedef struct {
    U  I5;
    RP  I768;
    RP  I989;
} RmaTableAssignList;
typedef struct {
    RP  I980;
} RmaWakeupListCg;
typedef struct {
    U  I990;
    U  I672;
    RmaTimeStamp   I991[1];
} RmaTsArray;
typedef struct {
    U  iinput;
    RP  I992;
} RmaConditionsMdb;
typedef struct {
    RP  I847;
    RP  I993;
    RP  I695;
    U  I994;
    scalar  I956;
    scalar  I995;
    US  I996 :1;
    US  I997 :1;
    US  I998 :1;
    US  I999 :1;
    US  I1000 :1;
    US  I1001 :1;
    US  I1002 :5;
} RmaTcCoreSimple;
typedef struct {
    RP  I847;
    RP  I993;
    RP  I695;
    U  I994;
    scalar  I956;
    scalar  I995;
    US  I996 :1;
    US  I997 :1;
    US  I998 :1;
    US  I999 :1;
    US  I1000 :1;
    US  I1001 :1;
    US  I1002 :5;
    RP  I1003;
} RmaTcCoreConditional;
typedef struct {
    RP  I847;
    RP  I993;
    RP  I695;
    U  I994;
    scalar  I956;
    scalar  I995;
    US  I996 :1;
    US  I997 :1;
    US  I998 :1;
    US  I999 :1;
    US  I1000 :1;
    US  I1001 :1;
    US  I1002 :5;
    RP  I1003;
    RP  I1004;
} RmaTcCoreConditionalOpt;
typedef struct {
    RP  I847;
    RP  I993;
    RP  I695;
    U  I994;
    scalar  I956;
    scalar  I995;
    US  I996 :1;
    US  I997 :1;
    US  I998 :1;
    US  I999 :1;
    US  I1000 :1;
    US  I1001 :1;
    US  I1002 :5;
    RP  I1004;
    RP  I1005;
    U  I1006;
    RmaConditionsMdb   arr[1];
} RmaTcCoreConditionalMtc;
typedef struct {
    RP  I993;
    RP  I695;
    U  I994;
    scalar  I956;
    scalar  I995;
    US  I996 :1;
    US  I997 :1;
    US  I998 :1;
    US  I999 :1;
    US  I1000 :1;
    US  I1001 :1;
    US  I1002 :5;
} RmaTcCoreSimpleNoList;
typedef struct {
    RP  I993;
    RP  I695;
    U  I994;
    scalar  I956;
    scalar  I995;
    US  I996 :1;
    US  I997 :1;
    US  I998 :1;
    US  I999 :1;
    US  I1000 :1;
    US  I1001 :1;
    US  I1002 :5;
    RP  I1008;
} RmaTcCoreSimpleNoListMdb;
typedef struct {
    RP  I993;
    RP  I695;
    U  I994;
    scalar  I956;
    scalar  I995;
    US  I996 :1;
    US  I997 :1;
    US  I998 :1;
    US  I999 :1;
    US  I1000 :1;
    US  I1001 :1;
    US  I1002 :5;
    RP  I1003;
} RmaTcCoreConditionalNoList;
typedef struct {
    RP  I993;
    RP  I695;
    U  I994;
    scalar  I956;
    scalar  I995;
    US  I996 :1;
    US  I997 :1;
    US  I998 :1;
    US  I999 :1;
    US  I1000 :1;
    US  I1001 :1;
    US  I1002 :5;
    RP  I1003;
    RP  I1004;
} RmaTcCoreConditionalOptNoList;
typedef struct {
    RP  I993;
    RP  I695;
    U  I994;
    scalar  I956;
    scalar  I995;
    US  I996 :1;
    US  I997 :1;
    US  I998 :1;
    US  I999 :1;
    US  I1000 :1;
    US  I1001 :1;
    US  I1002 :5;
    RP  I1004;
    RP  I1005;
    U  I1006;
    RmaConditionsMdb   arr[1];
} RmaTcCoreConditionalMtcNoList;
typedef struct {
    RP  I993;
    RP  I695;
    U  I994;
    scalar  I956;
    scalar  I995;
    US  I996 :1;
    US  I997 :1;
    US  I998 :1;
    US  I999 :1;
    US  I1000 :1;
    US  I1001 :1;
    US  I1002 :5;
    RP  I1004;
    RP  I1005;
    RP  I1008;
    U  I1006;
    RmaConditionsMdb   arr[1];
} RmaTcCoreConditionalMtcNoListMdb;
typedef struct {
    RP  I993;
    RP  I695;
    U  I994;
    scalar  I956;
    scalar  I995;
    US  I996 :1;
    US  I997 :1;
    US  I998 :1;
    US  I999 :1;
    US  I1000 :1;
    US  I1001 :1;
    US  I1002 :5;
    RP  I1003;
    RP  I1008;
} RmaTcCoreConditionalNoListMdb;
typedef struct {
    RP  I993;
    RP  I695;
    U  I994;
    scalar  I956;
    scalar  I995;
    US  I996 :1;
    US  I997 :1;
    US  I998 :1;
    US  I999 :1;
    US  I1000 :1;
    US  I1001 :1;
    US  I1002 :5;
    U  I1009;
    RP  I1010;
    RP  I1011;
    RP  I1003;
    RP  I1012;
    RP  I1013;
    RmaTimeStamp  I1014;
} RmaTcCoreNochange;
typedef struct {
    RP  I1015;
    RP  I847;
} RmaTcCoreNochangeList;
typedef struct {
    RP  I992;
    RmaTimeStamp  I1016;
    scalar  I1017;
} RmaConditionalTSLoadNoList;
typedef struct {
    RP  I847;
    RP  I992;
    RmaTimeStamp  I1016;
    scalar  I1017;
} RmaConditionalTSLoad;
typedef struct {
    RmaTimeStamp  I1016;
    scalar  I1017;
    US  I956;
    RP  I1004;
} RmaConditionalTSLoadOptNoList;
typedef struct {
    RP  I847;
    RmaTimeStamp  I1016;
    scalar  I1017;
    US  I956;
    RP  I1004;
} RmaConditionalTSLoadOpt;
typedef struct {
    RP  I1004;
    RP  I1018;
    U  I1006;
    RmaConditionsMdb   arr[1];
} RmaConditionalTSLoadMtcNoList;
typedef struct {
    RP  I1008;
    RP  I1004;
    RP  I1018;
    U  I1006;
    RmaConditionsMdb   arr[1];
} RmaConditionalTSLoadMtcNoListMdb;
typedef struct {
    RP  I847;
    RP  I1004;
    RP  I1018;
    U  I1006;
    RmaConditionsMdb   arr[1];
} RmaConditionalTSLoadMtc;
typedef struct {
    U  I1019;
    U  I1020;
    FlatNodeNum  I1021;
    U  I855;
    U  I1022;
    U  I1023;
    RmaIbfPcode  I952;
    union {
        scalar  I1024;
        vec32  I1025;
        scalar  * I1026;
        vec32  * I1027;
    } val;
} RmaScanSwitchData;
typedef struct {
    RP  I847;
    RP  I768;
    RP  I1028;
} RmaDoublyLinkedListElem;
typedef struct {
    RP  I1029;
    U  I1030 :1;
    U  I1031 :1;
    U  I1032 :1;
    U  I1033 :4;
    U  I599 :25;
    U  I1034;
} RmaSwitchGateInCbkListInfo;
typedef struct {
    union {
        RmaDoublyLinkedListElem  I1428;
        RmaSwitchGateInCbkListInfo  I2;
    } I669;
    RmaIbfPcode  I952;
} RmaSwitchGate;
typedef struct RmaNonEdgeLoadData1_ {
    US  I1035;
    scalar  val;
    scalar  I1036 :1;
    scalar  I1037 :1;
    scalar  I1038 :1;
    scalar  I1039 :1;
    scalar  I1040 :1;
    RP  I781;
    RP  I1041;
    RP  I1021;
    RP  I1042;
    RP  I1043;
} RmaNonEdgeLoadData1;
typedef struct RmaNonEdgeLoadHdr1_ {
    UB  I1036;
    UB  I1044;
    RmaNonEdgeLoadData1  * I975;
    RmaNonEdgeLoadData1  * I768;
} RmaNonEdgeLoadHdr1;
typedef struct RmaSubMasterSeqUdpLoad_ {
    RmaTableAssignList  * I1045;
    struct RmaSubMasterSeqUdpLoad_ * I1028;
    struct RmaSubMasterSeqUdpLoad_ * I847;
} RmaSubMasterSeqUdpLoad;
typedef struct RmaSubMasterSeqUdpList_ {
    RmaTableAssignList  * I1045;
    RmaSubMasterSeqUdpLoad  * I975;
    RmaSubMasterSeqUdpLoad  * I768;
} RmaSubMasterSeqUdpList;
typedef struct RmaChildClockProp_ {
    RP  I781;
    RP  I1047;
    RP  I1021;
    RP  pcode;
    scalar  val;
} RmaChildClockProp;
typedef struct RmaChildClockPropList1_ {
    RmaChildClockProp  * I975;
    RmaChildClockProp  * I768;
} RmaChildClockPropList1;
typedef struct {
    U  I5;
    U  I1048;
} RmaHDLCosimDUTGate;
struct clock_load {
    U  I183 :5;
    U  I184 :12;
    U  I185 :1;
    U  I186 :2;
    U  I187 :1;
    U  I188 :1;
    U  I189 :1;
    U  I190 :9;
    U  I191;
    U  I192;
    void (* pfn)(void * I194, char val);
};
typedef struct clock_data {
    U  I199 :1;
    U  I200 :1;
    U  I201 :1;
    U  I202 :1;
    U  I183 :5;
    U  I184 :12;
    U  I203 :6;
    U  I204 :1;
    U  I186 :2;
    U  I187 :1;
    U  I190 :1;
    U  I205;
    U  I206;
    U  I207;
    U  I191;
    U  I208;
    U  I209;
    U  I210;
    U  I211;
    U  I212;
} HdbsClockData;
struct clock_hiconn {
    U  I216;
    U  I217;
    U  I191;
    U  I186;
};
typedef struct _RmaDaiCg {
    RP  I1049;
    RP  I1050;
    U  I1051;
} RmaDaiCg;
typedef union _RmaCbkMemOptUnion {
    RP  I1049;
    RP  I1052;
    RP  I1053;
} RmaCbkMemOptUnion;
typedef struct _RmaDaiOptCg {
    RmaCbkMemOptUnion  I1054;
} RmaDaiOptCg;
struct futq_slot2 {
    U  I730;
    U   I731[32];
};
struct futq_slot1 {
    U  I727;
    struct futq_slot2  I728[32];
};
struct futq_info {
    U  I723;
    U  I724;
    struct futq_slot1  I725[32];
};
struct futq {
    struct futq * I713;
    struct futq * I715;
    RmaEblk  * I716;
    RmaEblk  * I717;
    U  I705;
};
struct sched_table {
    struct futq * I718;
    struct futq I719;
    struct hash_bucket * I720;
    struct hash_bucket * I722;
};
struct dummyq_struct {
    clock_struct  I1058;
    EBLK  * I1059;
    EBLK  * I1060;
    struct futq * I1061;
    struct futq * I1062;
    struct futq * I1063;
    struct sched_table * I1064;
    struct futq_info * I1066;
    U  I1068;
    U  I1069;
    U  I1070;
    struct millenium * I1071;
    EBLK  * I1073;
    EBLK  * I1074;
    EBLK  * I1075;
    EBLK  * I1076;
    EBLK  * I1077;
    EBLK  * I1078;
    EBLK  * I1079;
    EBLK  * I1080;
    EBLK  * I1081;
    EBLK  * I1082;
    EBLK  * I1083;
    EBLK  * I1084;
    EBLK  * I1085;
    EBLK  * I1086;
    EBLK  * I1087;
    EBLK  * I1088;
    EBLK  * I1089;
    EBLK  * I1090;
    MPS  * I1091;
};
typedef void (* FP)(void *  , scalar   );
typedef void (* FP1)(void *  );
typedef void (* FPRAP)(void *  , vec32  *  , U   );
typedef U  (* FPU1)(void *  );
typedef void (* FPV)(void *  , UB  *  );
typedef void (* FPVU)(void *  , UB  *  , U   );
typedef void (* FPLSEL)(void *  , scalar   , U   );
typedef void (* FPLSELV)(void *  , vec32  *  , U   , U   );
typedef void (* FPFPV)(UB  *  , UB  *  , U   , U   , U   , U   , U   , UB  *  , U   );
typedef void (* FPFA)(UB  *  , UB  *  , U   , U   , U   , U   , U   , U   , UB  *  , U   );
typedef void (* FPRPV)(UB  *  , U   , U   , U   );
typedef void (* FPEVCDLSEL)(void *  , scalar   , U   , UB  *  );
typedef void (* FPEVCDLSELV)(void *  , vec32  *  , U   , U   , UB  *  );
typedef void (* FPNTYPE_L)(void *  , void *  , U   , U   , UB  *  , UB  *  , UB  *  , UB  *  , UB  *  , UB  *  , UB  *  , U   );
typedef void (* FPNTYPE_H)(void *  , void *  , U   , U   , UB  *  , UB  *  , UB  *  , UB  *  , U   );
typedef void (* FPNTYPE_LPAP)(void *  , void *  , void *  , U   , U   , UB  *  , UB  *  , U   );
typedef void (* FPNTYPE_HPAP)(void *  , void *  , void *  , U   , U   , UB  *  , UB  *  , UB  *  , UB  *  , U   );
typedef struct _lqueue {
    EBLK  * I701;
    EBLK  * I1092;
    int I1093;
    struct _lqueue * I742;
} Queue;
typedef struct {
    EBLK  I1095;
    U  I1096;
    union {
        void * pHeap;
        Queue  * pList;
    } I669;
    Queue   I1097[1];
} Qhdr;
extern UB   Xvalchg[];
extern UB   X4val[];
extern UB   X3val[];
extern UB   X2val[];
extern UB   XcvtstrTR[];
extern UB   Xcvtstr[];
extern UB   Xbuf[];
extern UB   Xbitnot[];
extern UB   Xwor[];
extern UB   Xwand[];
extern U   Xbitnot4val[];
extern UB   globalTable1Input[];
extern unsigned long long vcs_clocks;
extern UB   Xunion[];
extern U  fRTFrcRelCbk;
extern FP  txpFnPtr;
extern FP   rmaFunctionArray[];
extern FP   rmaFunctionRtlArray[];
extern FP   rmaFunctionLRArray[];
extern U  rmaFunctionCount;
extern U  rmaFunctionLRCount;
extern U  rmaFunctionLRDummyCount;
extern UP  rmaFunctionDummyEndPtr;
extern UB  dummyScalar;
extern UB  fScalarIsForced;
extern UB  fScalarIsReleased;
extern U  fNotimingchecks;
extern RP  * iparr;
extern FP1  * rmaPostAnySchedFnPtr;
extern FP1  * rmaPostAnySchedFnSamplePtr;
extern FP1  * rmaPostAnySchedVFnPtr;
extern FP1  * rmaPostAnySchedWFnPtr;
extern FP1  * rmaPostAnySchedEFnPtr;
extern FP1  * rmaPostSchedUpdateClockStatusFnPtr;
extern FP1  * rmaPostSchedUpdateClockStatusNonCongruentFnPtr;
extern FP1  * rmaPostSchedUpdateEvTrigFnPtr;
extern FP1  * rmaSched0UpdateEvTrigFnPtr;
extern FP1  * rmaPostSchedRecoveryResetDbsFnPtr;
extern U  fGblDataOrTime0Prop;
extern UB   rmaEdgeStatusValArr[];
extern FP1  * propForceCbkSPostSchedCgFnPtr;
extern FP1  * propForceCbkMemoptSPostSchedCgFnPtr;
extern UB  * ptableGbl;
extern UB  * expandedClkValues;
extern US   xedges[];
extern Qhdr  * lvlQueue;
extern U  mhdl_delta_count;
extern U  ignoreSchedForScanOpt;
extern U  fignoreSchedForDeadComboCloud;
extern int fZeroUser;
extern U  fEveBusPullVal;
extern U  fEveBusPullFlag;
extern UB  fNettypeIsForced;
extern UB  fNettypeIsReleased;
extern EBLK  * peblkFutQ1Head;
extern EBLK  * peblkFutQ1Tail;
extern US  * edgeActionT;
extern unsigned long long * derivedClk;
extern U  fHashTableSize;
extern U  fSkipStrChangeOnDelay;
extern U  fLoopDetectMode;
extern int gFLoopDectCodeEna;
extern U  fLoopReportRT;


extern void *mempcpy(void* s1, void* s2, unsigned n);
extern UB* rmaEvalDelays(UB* pcode, scalar val);
extern UB* rmaEvalDelaysV(UB* pcode, vec32* pval);
extern void rmaPopTransEvent(UB* pcode);
extern void rmaSetupFuncArray(UP* ra, U c, U w);
extern void rmaSetupRTLoopReportPtrs(UP* funcs, UP* rtlFuncs, U cnt, U cntDummy, UP end);
extern void SinitHsimPats(void);
extern void VVrpDaicb(void* ip, U nIndex);
extern int SDaicb(void *ip, U nIndex);
extern void SDaicbForHsimNoFlagScalar(void* pDaiCb, unsigned char value);
extern void SDaicbForHsimNoFlagStrengthScalar(void* pDaiCb, unsigned char value);
extern void SDaicbForHsimNoFlag(void* pRmaDaiCg, unsigned char value);
extern void SDaicbForHsimNoFlag2(void* pRmaDaiCg, unsigned char value);
extern void SDaicbForHsimWithFlag(void* pRmaDaiCg, unsigned char value);
extern void SDaicbForHsimNoFlagFrcRel(void* pRmaDaiCg, unsigned char reason, int msb, int lsb, int ndx);
extern void SDaicbForHsimNoFlagFrcRel2(void* pRmaDaiCg, unsigned char reason, int msb, int lsb, int ndx);
extern void VcsHsimValueChangeCB(void* pRmaDaiCg, void* pValue, unsigned int valueFormat);
extern U isNonDesignNodeCallbackList(void* pRmaDaiCg);
extern void SDaicbForHsimCbkMemOptNoFlagScalar(void* pDaiCb, unsigned char value, unsigned char isStrength);
extern void SDaicbForHsimCbkMemOptWithFlagScalar(void* pDaiCb, unsigned char value, unsigned char isStrength);
extern void SDaicbForHsimCbkMemOptNoFlagScalar(void* pDaiCb, unsigned char value, unsigned char isStrength);
extern void SDaicbForHsimCbkMemOptWithFlagScalar(void* pDaiCb, unsigned char value, unsigned char isStrength);
extern void VVrpNonEventNonRegdScalarForHsimOptCbkMemopt(void* ip, U nIndex);
extern void SDaicbForHsimCbkMemOptNoFlagDynElabScalar(U* mem, unsigned char value, unsigned char isStrength);
extern void SDaicbForHsimCbkMemOptWithFlagDynElabScalar(U* mem, unsigned char value, unsigned char isStrength);
extern void SDaicbForHsimCbkMemOptNoFlagDynElabFrcRel(U* mem, unsigned char reason, int msb, int lsb, int ndx);
extern void SDaicbForHsimCbkMemOptNoFlagFrcRel(void* pDaiCb, unsigned char reason, int msb, int lsb, int ndx);
extern void hsimDispatchCbkMemOptForVcd(RP p, U val);
extern void* hsimGetCbkMemOptCallback(RP p);
extern void hsimDispatchCbkMemOptNoDynElabS(RP* p, U val, U isStrength);
extern void* hsimGetCbkPtrNoDynElab(RP p);
extern void hsimDispatchCbkMemOptDynElabS(U** pvcdarr, U** pcbkarr, U val, U isScalForced, U isScalReleased, U isStrength);
extern void hsimDispatchCbkMemOptNoDynElabVector(RP* /*RmaDaiOptCg* */p, void* pval, U /*RmaValueType*/ vt, U cbits);
extern void copyAndPropRootCbkCgS(RmaRootCbkCg* pRootCbk, scalar val);
extern void copyAndPropRootCbkCgV(RmaRootCbkCg* rootCbk, vec32* pval);
extern void copyAndPropRootCbkCgW(RmaRootCbkCg* rootCbk, vec32* pval);
extern void copyAndPropRootCbkCgE(RmaRootCbkCg* rootCbk, scalar* pval);
extern void dumpRootVcdCg(RmaRootVcdCg* pRootVcd, scalar val);
extern void Wsvvar_callback_non_dynamic1(RP* ptr, int);
extern void rmaExecEvSyncList(RP plist);
extern void Wsvvar_callback_virt_intf(RP* ptr);
extern void Wsvvar_callback_hsim_var(RP* ptr);
extern void checkAndConvertVec32To2State(vec32* value, vec32* svalue, U cbits, U* pforcedBits);
extern unsigned int fGblDataOrTime0Prop;
extern void SchedSemiLerMP1(UB* pmps, U partId);
extern void SchedSemiLerMPO(UB* pmpso, U partId);
extern void rmaDummyPropagate(void);
extern RP rmaTestCg(RP pcode, U vt, UB* value);
extern void hsUpdateModpathTimeStamp(UB* pmps);
extern void doMpd32One(UB* pmps);
extern void doMpdCommon(MPS* pmps);
extern TimeStamp GET_DIFF_DELAY_FUNC(TimeStamp ts);
extern void SchedSemiLerMP(UB* ppulse, U partId);
extern EBLK *peblkFutQ1Head;
extern EBLK *peblkFutQ1Tail;
extern void scheduleuna(UB *e, U t);
extern void scheduleuna_mp(EBLK *e, unsigned t);
extern void schedule(UB *e, U t);
extern void sched_hsopt(struct dummyq_struct * pQ, EBLK *e, U t);
extern void sched_millenium(struct dummyq_struct * pQ, void *e, U thigh, U t);
extern void schedule_1(EBLK *e);
extern void sched0(UB *e);
extern void sched0Raptor(UB *e);
extern void sched0lq(UB *e);
extern void sched0lqnc(EBLK *e);
extern void sched0una(UB *e);
extern void sched0una_th(struct dummyq_struct *pq, UB *e);
extern void hsopt_sched0u_th(struct dummyq_struct *pq, UB *e);
extern void scheduleuna_mp_th(struct dummyq_struct *pq, EBLK *e, unsigned t);
extern void schedal(UB *e);
extern void sched0_th(struct dummyq_struct * pQ, EBLK *e);
extern void sched0u(UB *e);
extern void sched0u_th(struct dummyq_struct *pq, UB *e);
extern void sched0_hsim_front_th(struct dummyq_struct * pQ, UB *e);
extern void sched0_hsim_frontlq_th(struct dummyq_struct * pQ, UB *e);
extern void sched0lq_th(struct dummyq_struct * pQ, UB *e);
extern void schedal_th(struct dummyq_struct * pQ, UB *e);
extern void scheduleuna_th(struct dummyq_struct * pQ, void *e, U t);
extern void schedule_th(struct dummyq_struct * pQ, UB *e, U t);
extern void schedule_1_th(struct dummyq_struct * pQ, EBLK *peblk);
extern void SetupLER_th(struct dummyq_struct * pQ, EBLK *e);
extern void FsdbReportClkGlitch(UB*,U);
extern void SchedSemiLer_th(struct dummyq_struct * pQ, EBLK *e);
extern void SchedSemiLerTXP_th(struct dummyq_struct * pQ, EBLK *e);
extern void SchedSemiLerTXPFreeVar_th(struct dummyq_struct * pQ, EBLK *e);
extern U getVcdFlags(UB *ip);
extern void VVrpNonEventNonRegdScalarForHsimOpt(void* ip, U nIndex);
extern void VVrpNonEventNonRegdScalarForHsimOpt2(void* ip, U nIndex);
extern void SchedSemiLerTBReactiveRegion(struct eblk* peblk);
extern void SchedSemiLerTBReactiveRegion_th(struct eblk* peblk, U partId);
extern void SchedSemiLerTr(UB* peblk, U partId);
extern void SchedSemiLerNBA(UB* peblk, U partId);
extern void NBA_Semiler(void *ip, void *pNBS);
extern void sched0sd_hsim(UB* peblk);
extern void appendNtcEvent(UB* phdr, scalar s, U schedDelta);
extern void appendTransEventS(RmaTransEventHdr* phdr, scalar s, U schedDelta);
extern void schedRetainHsim(MPS* pMPS, scalar sv, scalar pv);
extern void updateRetainHsim(MPS* pMPS,scalar sv, scalar pv);
extern void hsimRegisterEdge(void* sm,  scalar s);
extern U pvcsGetPartId();
extern void HsimPVCSPartIdCheck(U instNo);
extern void debug_func(U partId, struct dummyq_struct* pQ, EBLK* EblkLastEventx); 
extern struct dummyq_struct* pvcsGetQ(U thid);
extern EBLK* pvcsGetLastEventEblk(U thid);
extern void insertTransEvent(RmaTransEventHdr* phdr, scalar s, scalar pv, scalar resval, U schedDelta, int re, UB* predd, U fpdd);
extern void insertNtcEventRF(RmaTransEventHdr* phdr, scalar s, scalar pv, scalar resval, U schedDelta, U* delays);
extern U doTimingViolation(RmaTimeStamp ts,RP* pdata, U fskew, U limit, U floaded, U fcondopt, RmaTimeStamp tsNochange);
extern void sched_gate_hsim(EBLK* peblk, unsigned t, RP* offset, U gd_info, U encodeInPcode, void* propValue);
extern int getCurSchedRegion();
extern FP getRoutPtr(RP, U);
extern U rmaChangeCheckAndUpdateE(scalar* pvalDst, scalar* pvalSrc, U cbits);
extern void rmaUpdateE(scalar* pvalDst, scalar* pvalSrc, U cbits);
extern U rmaChangeCheckAndUpdateEFromW(scalar* pvalDst, vec32* pvalSrc, U cbits);
extern void rmaLhsPartSelUpdateE(scalar* pvalDst, scalar* pvalSrc, U index, U width);
extern void rmaUpdateWithForceSelectorE(scalar* pvalDst, scalar* pvalSrc, U cbits, U* pforceSelector);
extern void rmaUpdateWFromE(vec32* pvalDst, scalar* pvalSrc, U cbits);
extern U rmaLhsPartSelWithChangeCheckE(scalar* pvalDst, scalar* pvalSrc, U index, U width);
extern void rmaLhsPartSelWFromE(vec32* pvalDst, scalar* pvalSrc, U index,U width);
extern U rmaChangeCheckAndUpdateW(vec32* pvalDst, vec32* pvalSrc, U cbits);
extern void rmaUpdateW(vec32* pvalDst, vec32* pvalSrc, U cbits);
extern void rmaUpdateEFromW(scalar* pvalDst, vec32* pvalSrc, U cbits);
extern U rmaLhsPartSelWithChangeCheckW(vec32* pvalDst, vec32* pvalSrc, U index,U width);
extern void rmaLhsPartSelEFromW(scalar* pvalDst, vec32* pvalSrc, U index,U width);
extern U rmaLhsPartSelWithChangeCheckEFromW(scalar* pvalDst, vec32* pvalSrc, U index,U width);
extern void rmaLhsPartSelUpdateW(vec32* pvalDst, vec32* pvalSrc, U index, U width);
extern void rmaEvalWunionW(vec32* dst, vec32* src, U cbits, U count);
extern void rmaEvalWorW(vec32* dst, vec32* src, U cbits, U count);
extern void rmaEvalWandW(vec32* dst, vec32* src, U cbits, U count);
extern void rmaEvalUnionE(scalar* dst, scalar* src, U cbits, U count, RP ptable);
typedef U RmaCgFunctionType;
extern RmaIbfPcode* rmaEvalPartSelectsW(vec32* pvec32, U startIndex, U onWidth, U offWidth, U count, RmaIbfPcode* pibfPcode, U fnonRootForce);
extern RmaIbfPcode* rmaEvalPartSelectsWLe32(vec32* pvec32, U startIndex, U onWidth, U offWidth, U count, RmaIbfPcode* pibfPcode, U fnonRootForce);
extern RmaIbfPcode* rmaEvalPartSelectsWToE(vec32* pvec32, U startIndex, U onWidth, U offWidth, U count, RmaIbfPcode* pibfPcode, U fnonRootForce);
extern RmaIbfPcode* rmaEvalPartSelectsEToE(scalar* pv, U startIndex, U onWidth, U offWidth, U count, RmaIbfPcode* pibfPcode, U fnonRootForce, UB* pevcdStatus);
extern RmaIbfPcode* rmaEvalPartSelectsEToW(scalar* pv, U startIndex, U onWidth, U offWidth, U count, RmaIbfPcode* pibfPcode, U fnonRootForce);
extern U rmaEvalBitPosEdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitNegEdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitChangeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U VcsForceVecVCg(UB* pcode, UB* pval, UB* pvDst, UB* pvCur, U fullcbits, U ibeginSrc, U ibeginDst, U width, U/*RmaValueConvType*/ convtype, U/*RmaForceType*/ frcType, UB* prhs, UB* prhsDst, U frhs, U* pforcedbits, U fisRoot);
extern U VcsReleaseVecVCg(UB* pcode, UB* pvDst, U fullcbits, U ibeginDst, U width, UB* prhsDst, U frhs, U* pforcedbits, U fisRoot);
extern U VcsForceVecWCg(UB* pcode, UB* pval, UB* pvDst, UB* pvCur, U fullcbits, U ibeginSrc, U ibeginDst, U width, U/*RmaValueConvType*/ convtype, U /*RmaForceType*/ frcType, UB* prhs, UB* prhsDst, U frhs, U* pforcedbits, U fisRoot);
extern U VcsReleaseVecWCg(UB* pcode, UB* pvDst, U fullcbits, U ibeginDst, U width, UB* prhsDst, U frhs, U* pforcedbits, U fisRoot);
extern U VcsForceVecECg(UB* pcode, UB* pval, UB* pvDst, UB* pvCur, U fullcbits, U ibeginSrc, U ibeginDst, U width, U /*RmaValueConvType*/ convtype, U /*RmaForceType*/ frcType,UB* prhs, UB* prhsDst, U frhs, U* pforcedbits, U fisRoot);
extern U VcsForceVecACg(UB* pcode, UB* pval, UB* pvDst, UB* pvCur, U fullcbits, U ibeginSrc, U ibeginDst, U width, U /*RmaValueConvType*/ convtype, U /*RmaForceType*/ frcType,UB* prhs, UB* prhsDst, U frhs, U* pforcedbits, U fisRoot);
extern U VcsReleaseVecCg(UB* pcode, UB* pvDst, U ibeginDst, U width, U /*RmaValueType*/ type,U fisRoot, UB* prhsDst, U frhs, U* pforcedbits);
extern U VcsDriveBitsAndDoChangeCheckV(vec32* pvSel, vec32* pvCur, U fullcbits, U* pforcedbits, U isRoot);
extern U VcsDriveBitsAndDoChangeCheckW(vec32* pvSel, vec32* pvCur, U fullcbits, U* pforcedbits, U isRoot);
extern U VcsDriveBitsAndDoChangeCheckE(scalar* pvSel, scalar* pvCur, U fullcbits, U* pforcedbits, U isRoot);
extern void cgvecDebug_Eblk(UB* pcode);
extern U rmaCmpW(vec32* pvalDst, vec32* pvalSrc, U index, U width);
extern void copyVec32ArrMask(vec32* pv1, vec32* pv2, U len, U* mask);
extern void* memcpy(void*, const void*, size_t);
extern int memcmp(const void*, const void*, size_t);
extern void propagateScanOptPathVal(EBLK *peblk);
extern UB* rmaProcessScanSwitches(UB* pcode, scalar val);
extern UB* rmaProcessScanSwitchesV(UB* pcode, vec32 *pval);
extern UB* rmaProcessScanoptDump(UB* pcode, scalar val);
extern UB* rmaProcessScanoptDumpV(UB* pcode, vec32 *pval);
extern UB* rmaProcessScanChainOptSeqPrims(UB* pcode, scalar val);
extern void rmaProcessPvcsCcn(UB* pcode, scalar val);
extern void rmaProcessPvcsCcnE(UB* pcode, scalar* val);
extern void rmaProcessPvcsCcnW(UB* pcode, vec32* val);
extern void rmaProcessPvcsCcnV(UB* pcode, vec32* val);
extern void rmaProcessPvcsCcnCompiledS(UB* pcode, U offset, scalar ibnval);
extern void rmaProcessPvcsCcnCompiledV(UB* pcode, U offset, vec32* pval);
extern void schedResetRecoveryDbs(U cedges, EBLK* peblkFirst);
extern UB* rmaEvalUnaryOpV(UB* pcode, vec32* pval);
extern UB* rmaEvalBinaryOpV(UB* pcode, vec32* pval);
extern UB* rmaEvalBinaryOpVOneFanoutCount(UB* pcode, vec32* pval);
extern UB* rmaEvalBinaryOpVLargeFanoutCount(UB* pcode, vec32* pval);
extern UB* rmaEvalAndOpVOneFanoutCount(UB* pcode, vec32* value);
extern UB* rmaEvalAndOpVLargeFanoutCount(UB* pcode, vec32* value);
extern UB* rmaEvalAndOpV(UB* pcode, vec32* value);
extern UB* rmaEvalOrOpVOneFanoutCount(UB* pcode, vec32* value);
extern UB* rmaEvalOrOpVLargeFanoutCount(UB* pcode, vec32* value);
extern UB* rmaEvalOrOpV(UB* pcode, vec32* value);
extern UB* rmaEvalTernaryOpV(UB* pcode, vec32* pval);
extern UB* rmaEvalUnaryOpW(UB* pcode, vec32* pval);
extern UB* rmaEvalBinaryOpW(UB* pcode, vec32* pval);
extern UB* rmaEvalTernaryOpW(UB* pcode, vec32* pval);
extern UB* rmaEvalUnaryOpE(UB* pcode, scalar* pv);
extern UB* rmaEvalBinaryOpE(UB* pcode, scalar* pv);
extern UB* rmaEvalTernaryOpE(UB* pcode, scalar* pv);
extern UB* rmaEvalTernaryOpS(UB* pcode, scalar val);
extern scalar rmaGetScalarFromWCg(vec32* pval, U index);
extern void rmaSetScalarInWCg(vec32* pval, U index, scalar s);
extern void rmaCountRaptorBits(void* pval, void* pvalPrev, U cbits, U vt);
extern void setHsimFunc(void* ip);
extern void unsetHsimFunc(void* ip);
extern UB* getEvcdStatusByFlagsE(scalar* pscalar, UB* pevcdTBDriverFlags, U cdrivers, UB* table, U cbits);
extern UB* getEvcdStatusByFlagsV(vec32* pvec32, UB* pevcdTBDriverFlags, U cdrivers, UB* table, U cbits);
extern UB* getEvcdStatusByFlagsS(scalar* pscalar, UB* pevcdTBDriverFlags, U cdrivers, UB* table);
extern UB* getSingleDrvEvcdStatusS(UB value, U fTBDriver);
extern UB* getSingleDrvEvcdStatusE(scalar* pscalars, U fTBDriver, U cbits);
extern UB* getSingleDrvEvcdStatusV(scalar* pscalars, U fTBDriver, U cbits);
extern UB* getEvcdStatusByDrvEvcdStatus(UB* pdrvevcdStatus, U cdrivers, UB* table, U cbits);
extern void evcdCallback(UP pcode, U cbits);
extern UB* getSavedEvcdStatus(void);
extern void saveEvcdStatus(UB*);
extern void mhdlMarkExport(void*, U);
extern void levelInsertQueue(int);
extern void VcsRciRtl(RP pcode);
extern U fLoopDetectMode;
extern int gFLoopDectCodeEna;
extern U fLoopReportRT;
extern void rtSched0LoopDectDumpProcess(void* e, void* rtn, void* PQ);
extern void pushHsimRtnCtxt(void* pcode);
extern void popHsimRtnCtxt();
extern EBLK* loopReportInlinedSched0Wrapper(EBLK *peblk);
extern void loopReportSched0Wrapper(EBLK *peblk, unsigned int sfType, unsigned int fTH, struct dummyq_struct* pq);
extern void loopReportSchedSemiLerWrapper(EBLK *peblk, int sfType);
extern void CallGraphPushNodeAndAddToGraph(UP flatNode, UP instNum, U dummy);
extern void CallGraphPopNode(void);
extern RP elabGetIpTpl(U in);
extern U rmaEvalBitBothEdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitEdgeQ1W(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitEdgeQXW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitEdgeQ0W(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEval01EdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEval0XEdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEval10EdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEval1XEdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalX1EdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalX0EdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitPosEdgeE(scalar* pvalCurr, scalar* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitNegEdgeE(scalar* pvalCurr, scalar* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitBothEdgeE(scalar* pvalCurr, scalar* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitEdgeQ1E(scalar* pvalCurr, scalar* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitEdgeQ0E(scalar* pvalCurr, scalar* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitChangeE(scalar* pvalCurr, scalar* pvalPrev, U cbits, U* pedges);
extern void rmaScheduleNbaGate(RP pcode, scalar val);
extern void rmaEvalRtlEdgeLoads(RmaRtlEdgeBlockHdr *phdr, US clkEdge, scalar clkVal, scalar prevClkVal, scalar val4,   scalar prevval4);
extern void rmaEvaluateDynamicGateLoadsCg(RP p, scalar s);
extern void rmaEvaluateFusedWithDynamicGateLoadsCg(RP p, scalar s);
extern void rmaScheduleGatedClockEdgeLoad(UB* p, US* ea, U fNonEdgeLoad, UB* plist, UB* pprevlist, scalar v);
extern void rmaRemoveNonEdgeLoads(UB* pcode);
extern void rmaRecordEvents(HsimNodeRecord *pnr);
extern void handlePCBs(UB* p, U i);
extern void markMasterClkOvaLists(U fdbs, RP p);
extern void rmaChildClockPropAfterWrite(UB* p);
extern void rmaSchedChildClockPropAfterWrite(UB* p, UB* pmasterList, UB val);
extern void HDLCosimProcessDUTInputChange(U inputId, void* val);
extern void rmaChangeListForMovedGates(UB clkVal, UB f10Edge, UB* subMasterVal, UB* plist, RP* p, U count);
extern U rmaIsS2State(scalar s);
extern U rmaIsV2State(vec32* pval, U cbits);
extern U rmaIsW2State(vec32* pval, U cbits);
extern U rmaIsE2State(scalar* pval, U cbits);
extern void rmaUpdateRecordFor2State(HsimNodeRecord* record, U f2state);
typedef void (*FuncPtr)();
static inline U asm_bsf (U in)
{
#if defined(linux)
    U out;
    asm ("movl %1, %%eax; bsf %%eax, %%eax; movl %%eax, %0;"
        :"=r"(out)
        :"r"(in)
        :"%eax"
        );
    return out;
#else
    return 0;
#endif
}


#ifdef __cplusplus
extern "C" {
#endif
void  hs_0_M_0_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_1_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_2_0__simv_daidir (UB  * pcode, vec32  * I934, U  I855);
void  hs_0_M_3_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_3_5__simv_daidir (UB  * pcode, UB  val);
void  hs_0_M_4_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_5_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_6_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_7_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_8_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_9_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_10_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_11_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_12_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_13_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_14_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_15_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_16_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_17_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_18_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_19_0__simv_daidir (UB  * pcode, scalar  val);
void  hsG_0__0 (struct dummyq_struct * I1105, EBLK  * I1106, U  I655);
#ifdef __cplusplus
}
#endif

#ifdef __cplusplus
  }
#endif
#endif /*__DO_RMAHDR_*/

